version: '3.2'
services:
  sevtech:
    build: .
    image: sevtech:latest
    restart: always
    stdin_open: true
    tty: true
    ports:
    - "25565:25565"
    volumes:
      - type: bind
        source: /docker/sevtech
        target: /data
      - type: bind
        source: ./overrides
        target: /tmp/overrides
